#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
KEEP_COUNT=2
DRY_RUN=false
SKIP_CONFIRM=false
NVIDIA_MODE="prompt"

usage() {
    cat <<EOF
Usage: $SCRIPT_NAME [OPTIONS]

Remove old kernel packages from Fedora Linux.

OPTIONS:
    -k, --keep N         Number of kernel versions to keep (default: 2)
    -n, --dry-run        Preview what would be removed without executing
    -y, --yes            Skip confirmation prompt
    -N, --include-nvidia Include old kmod-nvidia packages in removal
    -x, --exclude-nvidia Exclude kmod-nvidia packages from removal
    -h, --help           Show this help message

EXAMPLES:
    $SCRIPT_NAME                      # Keep 2 latest kernels, ask for confirmation
    $SCRIPT_NAME -n                  # Preview removals
    $SCRIPT_NAME -k 1                # Keep only the running kernel (not recommended)
    $SCRIPT_NAME -y                  # Remove without asking
    $SCRIPT_NAME -k 3 -n             # Keep 3 kernels, preview only
    $SCRIPT_NAME --exclude-nvidia     # Skip kmod-nvidia cleanup
    $SCRIPT_NAME --include-nvidia -y # Include nvidia packages, skip confirm

EOF
    exit 0
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -k|--keep)
                KEEP_COUNT="$2"
                if ! [[ "$KEEP_COUNT" =~ ^[0-9]+$ ]] || [[ "$KEEP_COUNT" -lt 1 ]]; then
                    echo "Error: --keep requires a positive number" >&2
                    exit 1
                fi
                shift 2
                ;;
            -n|--dry-run)
                DRY_RUN=true
                shift
                ;;
            -y|--yes)
                SKIP_CONFIRM=true
                shift
                ;;
            -N|--include-nvidia)
                NVIDIA_MODE="include"
                shift
                ;;
            -x|--exclude-nvidia)
                NVIDIA_MODE="exclude"
                shift
                ;;
            -h|--help)
                usage
                ;;
            *)
                echo "Unknown option: $1" >&2
                usage
                ;;
        esac
    done
}

check_root() {
    if [[ $EUID -eq 0 ]]; then
        echo "Error: Do not run this script as root. Use sudo." >&2
        exit 1
    fi
}

check_dnf() {
    if ! command -v dnf &>/dev/null; then
        echo "Error: dnf not found. This script is for Fedora Linux." >&2
        exit 1
    fi
}

# Get the running kernel version (major, minor, patch level)
#
# Reads the full kernel version from `uname -r` and extracts the
# major, minor, and patch level parts. Returns the extracted version
# number as a string.
#
# Example:
#
#   $ get_running_kernel_version
#   5.11.22
get_running_kernel_version() {
    local full_version
    full_version=$(uname -r)
    echo "$full_version" | sed -E 's/^([0-9]+\.[0-9]+\.[0-9]+).*/\1/'
}

# Get a list of all kernel packages installed on the system.
#
# This function uses `dnf rq` to get a list of all kernel packages
# installed on the system, and then uses `rpm -qa` to get a list
# of all packages that belong to each kernel version. The lists
# are merged and the resulting list is printed to stdout.
#
# The list of packages includes all kernel packages, except for
# kernel-headers and kernel-debug packages.
get_kernel_packages() {
    local kernels
    mapfile -t kernels < <(dnf rq --installonly --latest-limit=-1 2>/dev/null)
    
    local all_pkgs=()
    for kernel in "${kernels[@]}"; do
        mapfile -t pkgs < <(rpm -qa | grep "^${kernel//+/\\+}" | grep -vE '^(kernel-headers|kernel-debug)' || true)
        all_pkgs+=("${pkgs[@]}")
    done
    
    printf '%s\n' "${all_pkgs[@]}"
}

# Get a list of all kmod-nvidia packages that do not belong to any of
# the kernel versions in the given list.
#
# This function takes a list of kernel versions as arguments, and returns
# a list of all kmod-nvidia packages that do not belong to any of the
# given kernel versions. The list is printed to stdout.
#
# The list of packages is generated by using `rpm -qa` to get a list of
# all packages, and then filtering the list to only include packages
# that start with "kmod-nvidia". The filtered list is then iterated over,
# and for each package, it is checked if it belongs to any of the given
# kernel versions. If it does not belong to any of the given kernel
# versions, it is added to the list of packages to remove.
#
# Example:
#
#   $ get_nvidia_kmod_packages 5.11.22 5.11.23
#   kmod-nvidia-5.11.22-470.57.2.fc36.x86_64
get_nvidia_kmod_packages() {
    local -a kept_versions=("$@")
    local nvidia_pkgs
    mapfile -t nvidia_pkgs < <(rpm -qa 2>/dev/null | grep -E '^kmod-nvidia' || true)
    
    local to_remove=()
    for pkg in "${nvidia_pkgs[@]}"; do
        local should_keep=false
        for kept in "${kept_versions[@]}"; do
            if [[ "$pkg" == *"${kept}"* ]]; then
                should_keep=true
                break
            fi
        done
        [[ "$should_keep" == "false" ]] && to_remove+=("$pkg")
    done
    
    printf '%s\n' "${to_remove[@]}"
}

# Remove old kernel packages from the system.
#
# This function takes three arguments:
#   keep_count: The number of kernel versions to keep.
#   dry_run: Whether to perform a dry run or not.
#   nvidia_mode: Whether to include ("include"), exclude ("exclude"), or prompt
#                           the user ("prompt") about removing old kmod-nvidia packages.
#
# The function first determines the running kernel version, and then
# gets a list of all kernel packages installed on the system.
# It filters the list to only include packages that belong to
# kernel versions that are not in the list of kept versions.
# The function then prints the list of packages to be removed, and
# prompts the user to confirm the removal.
#
# If the user confirms, the function removes the packages using `dnf remove`.
# If the user does not confirm, the function exits without making any changes.
#
# If the function is called with `dry_run` set to true, it will not make any
# changes to the system.
#
# The function also handles the removal of old kmod-nvidia packages based on
# the `nvidia_mode` argument. If `nvidia_mode` is set to "include", it will
# include old kmod-nvidia packages in the removal list. If it is set to "exclude",
# it will skip removing old kmod-nvidia packages. If it is set to "prompt", it will
# prompt the user to confirm the removal of old kmod-nvidia packages.
#
# The function returns 0 on success, and 1 on failure.
remove_old_kernels() {
    local keep_count="$1"
    local dry_run="$2"
    local nvidia_mode="$3"
    
    local running_kernel_version
    running_kernel_version=$(get_running_kernel_version)
    echo "Running kernel version: $running_kernel_version"
    echo "Keeping $keep_count kernel version(s)"
    echo
    
    local kernel_pkgs
    mapfile -t kernel_pkgs < <(get_kernel_packages)
    
    local unique_versions=()
    for pkg in "${kernel_pkgs[@]}"; do
        if [[ "$pkg" =~ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            local ver="${BASH_REMATCH[1]}"
            local found=false
            for v in "${unique_versions[@]}"; do
                [[ "$v" == "$ver" ]] && found=true && break
            done
            [[ "$found" == "false" ]] && unique_versions+=("$ver")
        fi
    done
    
    IFS=$'\n' sorted_versions=($(sort -V <<<"${unique_versions[*]}"))
    unset IFS
    
    local to_remove_versions=("${sorted_versions[@]:0:${#sorted_versions[@]}-keep_count+1}")
    
    if [[ ${#to_remove_versions[@]} -eq 0 ]] || [[ -z "${to_remove_versions[*]}" ]]; then
        echo "No old kernel packages to remove."
        return 0
    fi
    
    local to_remove=()
    for pkg in "${kernel_pkgs[@]}"; do
        for ver in "${to_remove_versions[@]}"; do
            if [[ "$pkg" =~ ([0-9]+\.[0-9]+\.[0-9]+) ]] && [[ "${BASH_REMATCH[1]}" == "$ver" ]]; then
                to_remove+=("$pkg")
                break
            fi
        done
    done
    
    local kept_full_versions=()
    for ver in "${sorted_versions[@]:${#sorted_versions[@]}-keep_count}"; do
        for pkg in "${kernel_pkgs[@]}"; do
            if [[ "$pkg" =~ ([0-9]+\.[0-9]+\.[0-9]+-[0-9]+\.fc[0-9]+\..+) ]] && [[ "${BASH_REMATCH[1]}" == "$ver" ]]; then
                local full_ver="${BASH_REMATCH[0]}"
                local found=false
                for kv in "${kept_full_versions[@]}"; do
                    [[ "$kv" == "$full_ver" ]] && found=true && break
                done
                [[ "$found" == "false" ]] && kept_full_versions+=("$full_ver")
                break
            fi
        done
    done
    
    local nvidia_pkgs
    mapfile -t nvidia_pkgs < <(get_nvidia_kmod_packages "${kept_full_versions[@]}")
    
    if [[ ${#nvidia_pkgs[@]} -gt 0 ]] && [[ "$nvidia_mode" != "exclude" ]]; then
        if [[ "$nvidia_mode" == "prompt" ]]; then
            echo "Found ${#nvidia_pkgs[@]} old kmod-nvidia package(s) to remove."
            read -rp "Remove them as well? [Y/n]: " ans
            if [[ "$ans" =~ ^[Nn]$ ]]; then
                echo "Skipping kmod-nvidia packages."
                unset nvidia_pkgs
            fi
        fi
        to_remove+=("${nvidia_pkgs[@]}")
    elif [[ "$nvidia_mode" == "exclude" ]]; then
        echo "Skipping kmod-nvidia packages (--exclude-nvidia)."
    fi
    
    if [[ ${#to_remove[@]} -eq 0 ]]; then
        echo "No old kernel or kmod-nvidia packages to remove."
        return 0
    fi
    
    echo "Packages to be removed:"
    printf '  %s\n' "${to_remove[@]}"
    echo
    
    local total_size
    total_size=$(sudo rpm --assumeno -e --justdb "${to_remove[@]}" 2>&1 | grep -oP '(?<=Total download size: )[0-9.]+[KMG]' | head -1 || echo "unknown")
    if [[ "$total_size" != "unknown" ]] && [[ -n "$total_size" ]]; then
        echo "Space to be freed: ~$total_size"
        echo
    fi
    
    if [[ "$dry_run" == "true" ]]; then
        echo "[DRY-RUN] No changes were made."
        return 0
    fi
    
    if [[ ${#to_remove[@]} -gt 0 ]]; then
        sudo dnf remove -y "${to_remove[@]}" && echo "Cleanup completed." || echo "Cleanup failed."
    fi
}

# Main entry point.
#
# Parse command line arguments, check for root privileges and the
# presence of the `dnf` package manager.
#
# If the `--keep` option is set to 1, print a warning to the user
# about the potential risks of only keeping one kernel version.
#
# Finally, call `remove_old_kernels` to perform the actual cleanup.
main() {
    parse_args "$@"
    check_root
    check_dnf
    
    if [[ "$KEEP_COUNT" -eq 1 ]]; then
        echo "WARNING: Keeping only 1 kernel is not recommended."
        echo "If the new kernel fails, you may not be able to boot."
        echo "Consider using --keep 2 or higher for safety."
        echo
    fi
    
    remove_old_kernels "$KEEP_COUNT" "$DRY_RUN" "$NVIDIA_MODE"
}

main "$@"
